<<: !include "../hpack/module.yaml"
name:                servant-util
version:             0.2
synopsis:            Servant servers utilities.
description:
  Basement for common Servant combinators like filtering, sorting, pagination and semantical logging.
category:            Servant, Web

dependencies:
- aeson
- base >= 4.7 && < 5
- constraints
- containers
- data-default
- fmt
- http-types
- insert-ordered-containers
- lens
- megaparsec
- mtl
- pretty-terminal
- openapi3
- safe-exceptions
- servant
- servant-client
- servant-client-core
- servant-openapi3
- servant-server
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- swagger2
- text
- text-format
- time
- reflection
- regex-posix
- QuickCheck
- universum
- QuickCheck
- wai

library:
  source-dirs: src

<<: *ghc-options

executables:
  servant-util-examples:
    <<: *exec-common
    source-dirs:         examples

    dependencies:
      - aeson
      - servant-util
      - warp
      - wai-extra

tests:
  servant-util-test:
    <<: *test-common
    build-tools: hspec-discover:hspec-discover
    dependencies:
      - hspec
      - hspec-expectations
      - http-client
      - servant-util
      - QuickCheck
      - warp

<<: *default-extensions
