<<: !include "../hpack/module.yaml"
name:                servant-util-beam-pg
version:             0.1.0.1
synopsis:            Implementation of servant-util primitives for beam-postgres.
category:            Servant, Web, Database

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-postgres
- containers
- servant
- servant-client
- servant-client-core
- servant-server
- servant-util >= 0.1.0 && < 0.2
- text
- universum

library:
  source-dirs: src

<<: *ghc-options

executables:
  servant-util-beam-pg-examples:
    <<: *exec-common
    source-dirs:         examples

tests:
  servant-util-beam-pg-test:
    <<: *test-common
    build-tools: hspec-discover:hspec-discover
    dependencies:
      - hspec
      - servant-util-beam-pg
      - QuickCheck

<<: *default-extensions
