<<: !include "../hpack/module.yaml"
name:                servant-util-beam-pg
version:             0.1.0
synopsis:            Primitives implementation via beam-postgres.

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-postgres
- containers
- servant
- servant-client
- servant-client-core
- servant-generic
- servant-server
- servant-util >= 0.1.0 && < 0.2
- universum

library:
  source-dirs: src

  build-tools:
    - autoexporter

<<: *ghc-options

executables:
  servant-util-beam-pg-examples:
    <<: *exec-common
    source-dirs:         examples

tests:
  servant-util-beam-pg-test:
    <<: *test-common

<<: *default-extensions
